In [1]:
import numpy as np
import pandas as pd

In [2]:
admin = pd.read_excel('C:\\Users\\lzh-a\\Desktop\DA\\NZ_Admin_JOBS.xlsx')

In [3]:
admin.describe()

,字段1,字段1_link,字段2,字段3,字段4,字段5
count,2708,2708,2686,2708,2708,2708
unique,548,2708,475,147,54,93
top,Executive Assistant,https://www.seek.co.nz/job/50582301?type=promo...,Beyond Recruitment - Winner – Best Innovation ...,location: AucklandAucklandarea: Auckland Centr...,"27d ago,at",classification: Administration & Office Suppor...
freq,301,1,285,654,572,715

In [4]:
admin.head(5)

,字段1,字段1_link,字段2,字段3,字段4,字段5
0,Administrator,https://www.seek.co.nz/job/50582301?type=promo...,NaN,location: Bay of PlentyBay of Plentyarea: Taur...,"Featured,at,Private Advertiser",classification: Administration & Office Suppor...
1,Receptionist,https://www.seek.co.nz/job/50620889?type=promo...,Avenues Orthodontics,location: Bay of PlentyBay of Plentyarea: Taur...,"Featured,at",classification: Administration & Office Suppor...
2,Prosecutions Support Officer,https://www.seek.co.nz/job/50622169?type=stand...,New Zealand Police,location: AucklandAuckland,"4d ago,at",classification: Administration & Office Suppor...
3,Early Childhood Centre Administrator,https://www.seek.co.nz/job/50639620?type=stand...,Kew Pacific Island Early Learning Centre,location: SouthlandSouthlandarea: Invercargill...,"1h ago,at",classification: Administration & Office Suppor...
4,Business Support Administrator,https://www.seek.co.nz/job/50622432?type=stand...,NaN,location: CanterburyCanterburyarea: Christchur...,"4d ago,at,Private Advertiser",classification: Administration & Office Suppor...

In [5]:
admin.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2708 entries, 0 to 2707
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   字段1       2708 non-null   object
 1   字段1_link  2708 non-null   object
 2   字段2       2686 non-null   object
 3   字段3       2708 non-null   object
 4   字段4       2708 non-null   object
 5   字段5       2708 non-null   object
dtypes: object(6)
memory usage: 127.1+ KB

In [6]:
admin.columns = ['Position', 'Link', 'Company', 'Locations', 'Post Time', 'Classification']

In [7]:
admin.head()

,Position,Link,Company,Locations,Post Time,Classification
0,Administrator,https://www.seek.co.nz/job/50582301?type=promo...,NaN,location: Bay of PlentyBay of Plentyarea: Taur...,"Featured,at,Private Advertiser",classification: Administration & Office Suppor...
1,Receptionist,https://www.seek.co.nz/job/50620889?type=promo...,Avenues Orthodontics,location: Bay of PlentyBay of Plentyarea: Taur...,"Featured,at",classification: Administration & Office Suppor...
2,Prosecutions Support Officer,https://www.seek.co.nz/job/50622169?type=stand...,New Zealand Police,location: AucklandAuckland,"4d ago,at",classification: Administration & Office Suppor...
3,Early Childhood Centre Administrator,https://www.seek.co.nz/job/50639620?type=stand...,Kew Pacific Island Early Learning Centre,location: SouthlandSouthlandarea: Invercargill...,"1h ago,at",classification: Administration & Office Suppor...
4,Business Support Administrator,https://www.seek.co.nz/job/50622432?type=stand...,NaN,location: CanterburyCanterburyarea: Christchur...,"4d ago,at,Private Advertiser",classification: Administration & Office Suppor...

In [8]:
admin[admin['Locations'].str.contains(',')]

,Position,Link,Company,Locations,Post Time,Classification
12,Office Admin Assistant (10hrs per week),https://www.seek.co.nz/job/50597141?type=stand...,UIV Limited - Premier Insulation North Central,location: AucklandAucklandarea: Manukau & East...,"8d ago,at",$20 per hour
17,Part-time Health & Disability Administrative A...,https://www.seek.co.nz/job/50610748?type=stand...,LIFEWISE,location: AucklandAucklandarea: Auckland Centr...,"6d ago,at",$20 - $24.99 per hour
23,Reception/Administrator,https://www.seek.co.nz/job/50556340?type=promo...,Fishing and Leisure Group Limited,location: AucklandAucklandarea: Rodney & North...,"Featured,at",$19 to $22 per hour
25,Office Administrator,https://www.seek.co.nz/job/50621389?type=stand...,Brant Homes Limited,location: AucklandAucklandarea: Manukau & East...,"4d ago,at",$20 - $24.99 per hour
36,office administrator,https://www.seek.co.nz/job/50621878?type=stand...,Best Mates Pet Food,location: WaikatoWaikatoarea: Rest of WaikatoR...,"4d ago,at",$20 - $24.99 per hour
...,...,...,...,...,...,...
2700,Executive Assistant,https://www.seek.co.nz/job/50494228?type=stand...,Robert Walters,"location: WellingtonWellington,Attractive remu...","26d ago,at",Attractive remuneration
2701,Temporary Office Roles,https://www.seek.co.nz/job/50556279?type=stand...,Asset Recruitment Ltd,location: WaikatoWaikatoarea: HamiltonHamilton...,"14d ago,at",Competitive hourly rates $$
2704,Executive Assistant,https://www.seek.co.nz/job/50488000?type=stand...,one eighty recruitment,location: WellingtonWellingtonarea: Wellington...,"27d ago,at",Competitive hourly rate
2705,Temporary Office Roles,https://www.seek.co.nz/job/50524865?type=stand...,Asset Recruitment Ltd,location: WaikatoWaikatoarea: HamiltonHamilton...,"20d ago,at",Competitive hourly rates $$
2706,Temporary Office Roles,https://www.seek.co.nz/job/50477118?type=stand...,Asset Recruitment Ltd,location: WaikatoWaikatoarea: HamiltonHamilton...,"28d ago,at",Competitive hourly rates $$

In [9]:
admin[['Location', 'Area']] = admin['Locations'].str.split('area: ', expand = True)
admin

,Position,Link,Company,Locations,Post Time,Classification,Location,Area
0,Administrator,https://www.seek.co.nz/job/50582301?type=promo...,NaN,location: Bay of PlentyBay of Plentyarea: Taur...,"Featured,at,Private Advertiser",classification: Administration & Office Suppor...,location: Bay of PlentyBay of Plenty,TaurangaTauranga
1,Receptionist,https://www.seek.co.nz/job/50620889?type=promo...,Avenues Orthodontics,location: Bay of PlentyBay of Plentyarea: Taur...,"Featured,at",classification: Administration & Office Suppor...,location: Bay of PlentyBay of Plenty,TaurangaTauranga
2,Prosecutions Support Officer,https://www.seek.co.nz/job/50622169?type=stand...,New Zealand Police,location: AucklandAuckland,"4d ago,at",classification: Administration & Office Suppor...,location: AucklandAuckland,None
3,Early Childhood Centre Administrator,https://www.seek.co.nz/job/50639620?type=stand...,Kew Pacific Island Early Learning Centre,location: SouthlandSouthlandarea: Invercargill...,"1h ago,at",classification: Administration & Office Suppor...,location: SouthlandSouthland,InvercargillInvercargill
4,Business Support Administrator,https://www.seek.co.nz/job/50622432?type=stand...,NaN,location: CanterburyCanterburyarea: Christchur...,"4d ago,at,Private Advertiser",classification: Administration & Office Suppor...,location: CanterburyCanterbury,ChristchurchChristchurch
...,...,...,...,...,...,...,...,...
2703,Key Account Manager,https://www.seek.co.nz/job/50490062?type=stand...,Hays Talent Solutions,location: AucklandAucklandarea: Auckland Centr...,"27d ago,at",classification: Administration & Office Suppor...,location: AucklandAuckland,Auckland CentralAuckland Central
2704,Executive Assistant,https://www.seek.co.nz/job/50488000?type=stand...,one eighty recruitment,location: WellingtonWellingtonarea: Wellington...,"27d ago,at",Competitive hourly rate,location: WellingtonWellington,"Wellington CentralWellington Central,Competiti..."
2705,Temporary Office Roles,https://www.seek.co.nz/job/50524865?type=stand...,Asset Recruitment Ltd,location: WaikatoWaikatoarea: HamiltonHamilton...,"20d ago,at",Competitive hourly rates $$,location: WaikatoWaikato,"HamiltonHamilton,Competitive hourly rates $$"
2706,Temporary Office Roles,https://www.seek.co.nz/job/50477118?type=stand...,Asset Recruitment Ltd,location: WaikatoWaikatoarea: HamiltonHamilton...,"28d ago,at",Competitive hourly rates $$,location: WaikatoWaikato,"HamiltonHamilton,Competitive hourly rates $$"
2707,Executive Assistant,https://www.seek.co.nz/job/50496571?type=stand...,Alpha Recruitment - NZ,location: WellingtonWellington,"26d ago,at",classification: Administration & Office Suppor...,location: WellingtonWellington,None

In [10]:
admin['Location'].isna().sum()

0

In [11]:
admin['Area'].isna().sum()

541

In [12]:
admin['Location'] = admin['Location'].apply(lambda x: x[9:])

In [13]:
admin['Location']

0        Bay of PlentyBay of Plenty
1        Bay of PlentyBay of Plenty
2                  AucklandAuckland
3                SouthlandSouthland
4              CanterburyCanterbury
                   ...
2703               AucklandAuckland
2704           WellingtonWellington
2705                 WaikatoWaikato
2706                 WaikatoWaikato
2707           WellingtonWellington
Name: Location, Length: 2708, dtype: object

In [14]:
def deduplication(x):
    trim = x.strip()
    index = (trim + trim).find(trim,1)
    if index != -1:
        return trim[:index]
    else:
        return trim

In [15]:
admin['Location'] = admin['Location'].apply(deduplication)
admin['Location']

0       Bay of Plenty
1       Bay of Plenty
2            Auckland
3           Southland
4          Canterbury
            ...
2703         Auckland
2704       Wellington
2705          Waikato
2706          Waikato
2707       Wellington
Name: Location, Length: 2708, dtype: object

In [16]:
admin['Area'].fillna(value = 'Unknown', inplace = True)

In [17]:
admin['Area'] = admin['Area'].str.split(',', expand = True)[0]
admin['Area']

0                           TaurangaTauranga
1                           TaurangaTauranga
2                                    Unknown
3                   InvercargillInvercargill
4                   ChristchurchChristchurch
                        ...
2703        Auckland CentralAuckland Central
2704    Wellington CentralWellington Central
2705                        HamiltonHamilton
2706                        HamiltonHamilton
2707                                 Unknown
Name: Area, Length: 2708, dtype: object

In [18]:
admin['Area'] = admin['Area'].apply(deduplication)

In [19]:
admin['Area']

0                 Tauranga
1                 Tauranga
2                  Unknown
3             Invercargill
4             Christchurch
               ...
2703      Auckland Central
2704    Wellington Central
2705              Hamilton
2706              Hamilton
2707               Unknown
Name: Area, Length: 2708, dtype: object

In [20]:
admin['Area'].isna().sum()

0

In [21]:
admin.drop('Locations', axis = 1, inplace = True)

In [22]:
admin.head()

,Position,Link,Company,Post Time,Classification,Location,Area
0,Administrator,https://www.seek.co.nz/job/50582301?type=promo...,NaN,"Featured,at,Private Advertiser",classification: Administration & Office Suppor...,Bay of Plenty,Tauranga
1,Receptionist,https://www.seek.co.nz/job/50620889?type=promo...,Avenues Orthodontics,"Featured,at",classification: Administration & Office Suppor...,Bay of Plenty,Tauranga
2,Prosecutions Support Officer,https://www.seek.co.nz/job/50622169?type=stand...,New Zealand Police,"4d ago,at",classification: Administration & Office Suppor...,Auckland,Unknown
3,Early Childhood Centre Administrator,https://www.seek.co.nz/job/50639620?type=stand...,Kew Pacific Island Early Learning Centre,"1h ago,at",classification: Administration & Office Suppor...,Southland,Invercargill
4,Business Support Administrator,https://www.seek.co.nz/job/50622432?type=stand...,NaN,"4d ago,at,Private Advertiser",classification: Administration & Office Suppor...,Canterbury,Christchurch

In [23]:
admin.head()

,Position,Link,Company,Post Time,Classification,Location,Area
0,Administrator,https://www.seek.co.nz/job/50582301?type=promo...,NaN,"Featured,at,Private Advertiser",classification: Administration & Office Suppor...,Bay of Plenty,Tauranga
1,Receptionist,https://www.seek.co.nz/job/50620889?type=promo...,Avenues Orthodontics,"Featured,at",classification: Administration & Office Suppor...,Bay of Plenty,Tauranga
2,Prosecutions Support Officer,https://www.seek.co.nz/job/50622169?type=stand...,New Zealand Police,"4d ago,at",classification: Administration & Office Suppor...,Auckland,Unknown
3,Early Childhood Centre Administrator,https://www.seek.co.nz/job/50639620?type=stand...,Kew Pacific Island Early Learning Centre,"1h ago,at",classification: Administration & Office Suppor...,Southland,Invercargill
4,Business Support Administrator,https://www.seek.co.nz/job/50622432?type=stand...,NaN,"4d ago,at,Private Advertiser",classification: Administration & Office Suppor...,Canterbury,Christchurch

In [24]:
admin[['Classification', 'SubClassification']] = admin['Classification'].str.split('subClassification: ', expand = True)

In [25]:
admin.head()

,Position,Link,Company,Post Time,Classification,Location,Area,SubClassification
0,Administrator,https://www.seek.co.nz/job/50582301?type=promo...,NaN,"Featured,at,Private Advertiser",classification: Administration & Office Suppor...,Bay of Plenty,Tauranga,Office ManagementOffice Management
1,Receptionist,https://www.seek.co.nz/job/50620889?type=promo...,Avenues Orthodontics,"Featured,at",classification: Administration & Office Suppor...,Bay of Plenty,Tauranga,ReceptionistsReceptionists
2,Prosecutions Support Officer,https://www.seek.co.nz/job/50622169?type=stand...,New Zealand Police,"4d ago,at",classification: Administration & Office Suppor...,Auckland,Unknown,OtherOther
3,Early Childhood Centre Administrator,https://www.seek.co.nz/job/50639620?type=stand...,Kew Pacific Island Early Learning Centre,"1h ago,at",classification: Administration & Office Suppor...,Southland,Invercargill,Administrative AssistantsAdministrative Assist...
4,Business Support Administrator,https://www.seek.co.nz/job/50622432?type=stand...,NaN,"4d ago,at,Private Advertiser",classification: Administration & Office Suppor...,Canterbury,Christchurch,Client & Sales AdministrationClient & Sales Ad...

In [26]:
admin['Classification'].isna().sum()

0

In [27]:
admin['SubClassification'].isna().sum()

603

In [28]:
admin['SubClassification'].fillna('Unknown', inplace = True)

In [29]:
admin.head()

,Position,Link,Company,Post Time,Classification,Location,Area,SubClassification
0,Administrator,https://www.seek.co.nz/job/50582301?type=promo...,NaN,"Featured,at,Private Advertiser",classification: Administration & Office Suppor...,Bay of Plenty,Tauranga,Office ManagementOffice Management
1,Receptionist,https://www.seek.co.nz/job/50620889?type=promo...,Avenues Orthodontics,"Featured,at",classification: Administration & Office Suppor...,Bay of Plenty,Tauranga,ReceptionistsReceptionists
2,Prosecutions Support Officer,https://www.seek.co.nz/job/50622169?type=stand...,New Zealand Police,"4d ago,at",classification: Administration & Office Suppor...,Auckland,Unknown,OtherOther
3,Early Childhood Centre Administrator,https://www.seek.co.nz/job/50639620?type=stand...,Kew Pacific Island Early Learning Centre,"1h ago,at",classification: Administration & Office Suppor...,Southland,Invercargill,Administrative AssistantsAdministrative Assist...
4,Business Support Administrator,https://www.seek.co.nz/job/50622432?type=stand...,NaN,"4d ago,at,Private Advertiser",classification: Administration & Office Suppor...,Canterbury,Christchurch,Client & Sales AdministrationClient & Sales Ad...

In [30]:
admin['Classification'] = admin['Classification'].apply(deduplication)

In [31]:
admin.head()

,Position,Link,Company,Post Time,Classification,Location,Area,SubClassification
0,Administrator,https://www.seek.co.nz/job/50582301?type=promo...,NaN,"Featured,at,Private Advertiser",classification: Administration & Office Suppor...,Bay of Plenty,Tauranga,Office ManagementOffice Management
1,Receptionist,https://www.seek.co.nz/job/50620889?type=promo...,Avenues Orthodontics,"Featured,at",classification: Administration & Office Suppor...,Bay of Plenty,Tauranga,ReceptionistsReceptionists
2,Prosecutions Support Officer,https://www.seek.co.nz/job/50622169?type=stand...,New Zealand Police,"4d ago,at",classification: Administration & Office Suppor...,Auckland,Unknown,OtherOther
3,Early Childhood Centre Administrator,https://www.seek.co.nz/job/50639620?type=stand...,Kew Pacific Island Early Learning Centre,"1h ago,at",classification: Administration & Office Suppor...,Southland,Invercargill,Administrative AssistantsAdministrative Assist...
4,Business Support Administrator,https://www.seek.co.nz/job/50622432?type=stand...,NaN,"4d ago,at,Private Advertiser",classification: Administration & Office Suppor...,Canterbury,Christchurch,Client & Sales AdministrationClient & Sales Ad...

In [32]:
admin['SubClassification'] = admin['SubClassification'].apply(deduplication)

In [33]:
admin.head()

,Position,Link,Company,Post Time,Classification,Location,Area,SubClassification
0,Administrator,https://www.seek.co.nz/job/50582301?type=promo...,NaN,"Featured,at,Private Advertiser",classification: Administration & Office Suppor...,Bay of Plenty,Tauranga,Office Management
1,Receptionist,https://www.seek.co.nz/job/50620889?type=promo...,Avenues Orthodontics,"Featured,at",classification: Administration & Office Suppor...,Bay of Plenty,Tauranga,Receptionists
2,Prosecutions Support Officer,https://www.seek.co.nz/job/50622169?type=stand...,New Zealand Police,"4d ago,at",classification: Administration & Office Suppor...,Auckland,Unknown,Other
3,Early Childhood Centre Administrator,https://www.seek.co.nz/job/50639620?type=stand...,Kew Pacific Island Early Learning Centre,"1h ago,at",classification: Administration & Office Suppor...,Southland,Invercargill,Administrative Assistants
4,Business Support Administrator,https://www.seek.co.nz/job/50622432?type=stand...,NaN,"4d ago,at,Private Advertiser",classification: Administration & Office Suppor...,Canterbury,Christchurch,Client & Sales Administration

In [34]:
admin[['Post Time', 'featured at']] = admin['Post Time'].str.split(',', expand = True)[[0,2]]

In [35]:
admin.head()

,Position,Link,Company,Post Time,Classification,Location,Area,SubClassification,featured at
0,Administrator,https://www.seek.co.nz/job/50582301?type=promo...,NaN,Featured,classification: Administration & Office Suppor...,Bay of Plenty,Tauranga,Office Management,Private Advertiser
1,Receptionist,https://www.seek.co.nz/job/50620889?type=promo...,Avenues Orthodontics,Featured,classification: Administration & Office Suppor...,Bay of Plenty,Tauranga,Receptionists,None
2,Prosecutions Support Officer,https://www.seek.co.nz/job/50622169?type=stand...,New Zealand Police,4d ago,classification: Administration & Office Suppor...,Auckland,Unknown,Other,None
3,Early Childhood Centre Administrator,https://www.seek.co.nz/job/50639620?type=stand...,Kew Pacific Island Early Learning Centre,1h ago,classification: Administration & Office Suppor...,Southland,Invercargill,Administrative Assistants,None
4,Business Support Administrator,https://www.seek.co.nz/job/50622432?type=stand...,NaN,4d ago,classification: Administration & Office Suppor...,Canterbury,Christchurch,Client & Sales Administration,Private Advertiser

In [36]:
admin['featured at'].isna().sum()

2686

In [37]:
admin['featured at'].fillna('Unknown', inplace = True)

In [38]:
admin

,Position,Link,Company,Post Time,Classification,Location,Area,SubClassification,featured at
0,Administrator,https://www.seek.co.nz/job/50582301?type=promo...,NaN,Featured,classification: Administration & Office Suppor...,Bay of Plenty,Tauranga,Office Management,Private Advertiser
1,Receptionist,https://www.seek.co.nz/job/50620889?type=promo...,Avenues Orthodontics,Featured,classification: Administration & Office Suppor...,Bay of Plenty,Tauranga,Receptionists,Unknown
2,Prosecutions Support Officer,https://www.seek.co.nz/job/50622169?type=stand...,New Zealand Police,4d ago,classification: Administration & Office Suppor...,Auckland,Unknown,Other,Unknown
3,Early Childhood Centre Administrator,https://www.seek.co.nz/job/50639620?type=stand...,Kew Pacific Island Early Learning Centre,1h ago,classification: Administration & Office Suppor...,Southland,Invercargill,Administrative Assistants,Unknown
4,Business Support Administrator,https://www.seek.co.nz/job/50622432?type=stand...,NaN,4d ago,classification: Administration & Office Suppor...,Canterbury,Christchurch,Client & Sales Administration,Private Advertiser
...,...,...,...,...,...,...,...,...,...
2703,Key Account Manager,https://www.seek.co.nz/job/50490062?type=stand...,Hays Talent Solutions,27d ago,classification: Administration & Office Suppor...,Auckland,Auckland Central,Client & Sales Administration,Unknown
2704,Executive Assistant,https://www.seek.co.nz/job/50488000?type=stand...,one eighty recruitment,27d ago,Competitive hourly rate,Wellington,Wellington Central,Unknown,Unknown
2705,Temporary Office Roles,https://www.seek.co.nz/job/50524865?type=stand...,Asset Recruitment Ltd,20d ago,Competitive hourly rates $$,Waikato,Hamilton,Unknown,Unknown
2706,Temporary Office Roles,https://www.seek.co.nz/job/50477118?type=stand...,Asset Recruitment Ltd,28d ago,Competitive hourly rates $$,Waikato,Hamilton,Unknown,Unknown
2707,Executive Assistant,https://www.seek.co.nz/job/50496571?type=stand...,Alpha Recruitment - NZ,26d ago,classification: Administration & Office Suppor...,Wellington,Unknown,"PA, EA & Secretarial",Unknown

In [39]:
def apply_salary(x):
    if 'classification:' in x:
        return 'Unknown'
    else:
        return x

In [40]:
admin['Salary'] = admin['Classification'].apply(apply_salary)

In [41]:
admin

,Position,Link,Company,Post Time,Classification,Location,Area,SubClassification,featured at,Salary
0,Administrator,https://www.seek.co.nz/job/50582301?type=promo...,NaN,Featured,classification: Administration & Office Suppor...,Bay of Plenty,Tauranga,Office Management,Private Advertiser,Unknown
1,Receptionist,https://www.seek.co.nz/job/50620889?type=promo...,Avenues Orthodontics,Featured,classification: Administration & Office Suppor...,Bay of Plenty,Tauranga,Receptionists,Unknown,Unknown
2,Prosecutions Support Officer,https://www.seek.co.nz/job/50622169?type=stand...,New Zealand Police,4d ago,classification: Administration & Office Suppor...,Auckland,Unknown,Other,Unknown,Unknown
3,Early Childhood Centre Administrator,https://www.seek.co.nz/job/50639620?type=stand...,Kew Pacific Island Early Learning Centre,1h ago,classification: Administration & Office Suppor...,Southland,Invercargill,Administrative Assistants,Unknown,Unknown
4,Business Support Administrator,https://www.seek.co.nz/job/50622432?type=stand...,NaN,4d ago,classification: Administration & Office Suppor...,Canterbury,Christchurch,Client & Sales Administration,Private Advertiser,Unknown
...,...,...,...,...,...,...,...,...,...,...
2703,Key Account Manager,https://www.seek.co.nz/job/50490062?type=stand...,Hays Talent Solutions,27d ago,classification: Administration & Office Suppor...,Auckland,Auckland Central,Client & Sales Administration,Unknown,Unknown
2704,Executive Assistant,https://www.seek.co.nz/job/50488000?type=stand...,one eighty recruitment,27d ago,Competitive hourly rate,Wellington,Wellington Central,Unknown,Unknown,Competitive hourly rate
2705,Temporary Office Roles,https://www.seek.co.nz/job/50524865?type=stand...,Asset Recruitment Ltd,20d ago,Competitive hourly rates $$,Waikato,Hamilton,Unknown,Unknown,Competitive hourly rates $$
2706,Temporary Office Roles,https://www.seek.co.nz/job/50477118?type=stand...,Asset Recruitment Ltd,28d ago,Competitive hourly rates $$,Waikato,Hamilton,Unknown,Unknown,Competitive hourly rates $$
2707,Executive Assistant,https://www.seek.co.nz/job/50496571?type=stand...,Alpha Recruitment - NZ,26d ago,classification: Administration & Office Suppor...,Wellington,Unknown,"PA, EA & Secretarial",Unknown,Unknown

In [42]:
def apply_classification(x):
    if 'classification' in x:
        return x[15:]
    else:
        return 'Unknow'

In [43]:
admin['Classification'] = admin['Classification'].apply(apply_classification)

In [44]:
admin

,Position,Link,Company,Post Time,Classification,Location,Area,SubClassification,featured at,Salary
0,Administrator,https://www.seek.co.nz/job/50582301?type=promo...,NaN,Featured,Administration & Office SupportAdministration...,Bay of Plenty,Tauranga,Office Management,Private Advertiser,Unknown
1,Receptionist,https://www.seek.co.nz/job/50620889?type=promo...,Avenues Orthodontics,Featured,Administration & Office SupportAdministration...,Bay of Plenty,Tauranga,Receptionists,Unknown,Unknown
2,Prosecutions Support Officer,https://www.seek.co.nz/job/50622169?type=stand...,New Zealand Police,4d ago,Administration & Office SupportAdministration...,Auckland,Unknown,Other,Unknown,Unknown
3,Early Childhood Centre Administrator,https://www.seek.co.nz/job/50639620?type=stand...,Kew Pacific Island Early Learning Centre,1h ago,Administration & Office SupportAdministration...,Southland,Invercargill,Administrative Assistants,Unknown,Unknown
4,Business Support Administrator,https://www.seek.co.nz/job/50622432?type=stand...,NaN,4d ago,Administration & Office SupportAdministration...,Canterbury,Christchurch,Client & Sales Administration,Private Advertiser,Unknown
...,...,...,...,...,...,...,...,...,...,...
2703,Key Account Manager,https://www.seek.co.nz/job/50490062?type=stand...,Hays Talent Solutions,27d ago,Administration & Office SupportAdministration...,Auckland,Auckland Central,Client & Sales Administration,Unknown,Unknown
2704,Executive Assistant,https://www.seek.co.nz/job/50488000?type=stand...,one eighty recruitment,27d ago,Unknow,Wellington,Wellington Central,Unknown,Unknown,Competitive hourly rate
2705,Temporary Office Roles,https://www.seek.co.nz/job/50524865?type=stand...,Asset Recruitment Ltd,20d ago,Unknow,Waikato,Hamilton,Unknown,Unknown,Competitive hourly rates $$
2706,Temporary Office Roles,https://www.seek.co.nz/job/50477118?type=stand...,Asset Recruitment Ltd,28d ago,Unknow,Waikato,Hamilton,Unknown,Unknown,Competitive hourly rates $$
2707,Executive Assistant,https://www.seek.co.nz/job/50496571?type=stand...,Alpha Recruitment - NZ,26d ago,Administration & Office SupportAdministration...,Wellington,Unknown,"PA, EA & Secretarial",Unknown,Unknown

In [45]:
admin[['Classification1', 'Classification2', 'Classification3']] = admin['Classification'].str.split('&', n = 2, expand = True).fillna('Unknown')

In [46]:
admin

,Position,Link,Company,Post Time,Classification,Location,Area,SubClassification,featured at,Salary,Classification1,Classification2,Classification3
0,Administrator,https://www.seek.co.nz/job/50582301?type=promo...,NaN,Featured,Administration & Office SupportAdministration...,Bay of Plenty,Tauranga,Office Management,Private Advertiser,Unknown,Administration,Office SupportAdministration,Office Support
1,Receptionist,https://www.seek.co.nz/job/50620889?type=promo...,Avenues Orthodontics,Featured,Administration & Office SupportAdministration...,Bay of Plenty,Tauranga,Receptionists,Unknown,Unknown,Administration,Office SupportAdministration,Office Support
2,Prosecutions Support Officer,https://www.seek.co.nz/job/50622169?type=stand...,New Zealand Police,4d ago,Administration & Office SupportAdministration...,Auckland,Unknown,Other,Unknown,Unknown,Administration,Office SupportAdministration,Office Support
3,Early Childhood Centre Administrator,https://www.seek.co.nz/job/50639620?type=stand...,Kew Pacific Island Early Learning Centre,1h ago,Administration & Office SupportAdministration...,Southland,Invercargill,Administrative Assistants,Unknown,Unknown,Administration,Office SupportAdministration,Office Support
4,Business Support Administrator,https://www.seek.co.nz/job/50622432?type=stand...,NaN,4d ago,Administration & Office SupportAdministration...,Canterbury,Christchurch,Client & Sales Administration,Private Advertiser,Unknown,Administration,Office SupportAdministration,Office Support
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2703,Key Account Manager,https://www.seek.co.nz/job/50490062?type=stand...,Hays Talent Solutions,27d ago,Administration & Office SupportAdministration...,Auckland,Auckland Central,Client & Sales Administration,Unknown,Unknown,Administration,Office SupportAdministration,Office Support
2704,Executive Assistant,https://www.seek.co.nz/job/50488000?type=stand...,one eighty recruitment,27d ago,Unknow,Wellington,Wellington Central,Unknown,Unknown,Competitive hourly rate,Unknow,Unknown,Unknown
2705,Temporary Office Roles,https://www.seek.co.nz/job/50524865?type=stand...,Asset Recruitment Ltd,20d ago,Unknow,Waikato,Hamilton,Unknown,Unknown,Competitive hourly rates $$,Unknow,Unknown,Unknown
2706,Temporary Office Roles,https://www.seek.co.nz/job/50477118?type=stand...,Asset Recruitment Ltd,28d ago,Unknow,Waikato,Hamilton,Unknown,Unknown,Competitive hourly rates $$,Unknow,Unknown,Unknown
2707,Executive Assistant,https://www.seek.co.nz/job/50496571?type=stand...,Alpha Recruitment - NZ,26d ago,Administration & Office SupportAdministration...,Wellington,Unknown,"PA, EA & Secretarial",Unknown,Unknown,Administration,Office SupportAdministration,Office Support

In [47]:
admin['Company'].fillna(admin['featured at'], inplace = True)

In [48]:
admin

,Position,Link,Company,Post Time,Classification,Location,Area,SubClassification,featured at,Salary,Classification1,Classification2,Classification3
0,Administrator,https://www.seek.co.nz/job/50582301?type=promo...,Private Advertiser,Featured,Administration & Office SupportAdministration...,Bay of Plenty,Tauranga,Office Management,Private Advertiser,Unknown,Administration,Office SupportAdministration,Office Support
1,Receptionist,https://www.seek.co.nz/job/50620889?type=promo...,Avenues Orthodontics,Featured,Administration & Office SupportAdministration...,Bay of Plenty,Tauranga,Receptionists,Unknown,Unknown,Administration,Office SupportAdministration,Office Support
2,Prosecutions Support Officer,https://www.seek.co.nz/job/50622169?type=stand...,New Zealand Police,4d ago,Administration & Office SupportAdministration...,Auckland,Unknown,Other,Unknown,Unknown,Administration,Office SupportAdministration,Office Support
3,Early Childhood Centre Administrator,https://www.seek.co.nz/job/50639620?type=stand...,Kew Pacific Island Early Learning Centre,1h ago,Administration & Office SupportAdministration...,Southland,Invercargill,Administrative Assistants,Unknown,Unknown,Administration,Office SupportAdministration,Office Support
4,Business Support Administrator,https://www.seek.co.nz/job/50622432?type=stand...,Private Advertiser,4d ago,Administration & Office SupportAdministration...,Canterbury,Christchurch,Client & Sales Administration,Private Advertiser,Unknown,Administration,Office SupportAdministration,Office Support
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2703,Key Account Manager,https://www.seek.co.nz/job/50490062?type=stand...,Hays Talent Solutions,27d ago,Administration & Office SupportAdministration...,Auckland,Auckland Central,Client & Sales Administration,Unknown,Unknown,Administration,Office SupportAdministration,Office Support
2704,Executive Assistant,https://www.seek.co.nz/job/50488000?type=stand...,one eighty recruitment,27d ago,Unknow,Wellington,Wellington Central,Unknown,Unknown,Competitive hourly rate,Unknow,Unknown,Unknown
2705,Temporary Office Roles,https://www.seek.co.nz/job/50524865?type=stand...,Asset Recruitment Ltd,20d ago,Unknow,Waikato,Hamilton,Unknown,Unknown,Competitive hourly rates $$,Unknow,Unknown,Unknown
2706,Temporary Office Roles,https://www.seek.co.nz/job/50477118?type=stand...,Asset Recruitment Ltd,28d ago,Unknow,Waikato,Hamilton,Unknown,Unknown,Competitive hourly rates $$,Unknow,Unknown,Unknown
2707,Executive Assistant,https://www.seek.co.nz/job/50496571?type=stand...,Alpha Recruitment - NZ,26d ago,Administration & Office SupportAdministration...,Wellington,Unknown,"PA, EA & Secretarial",Unknown,Unknown,Administration,Office SupportAdministration,Office Support

In [49]:
admin.drop('featured at', axis = 1, inplace = True)

In [50]:
admin

,Position,Link,Company,Post Time,Classification,Location,Area,SubClassification,Salary,Classification1,Classification2,Classification3
0,Administrator,https://www.seek.co.nz/job/50582301?type=promo...,Private Advertiser,Featured,Administration & Office SupportAdministration...,Bay of Plenty,Tauranga,Office Management,Unknown,Administration,Office SupportAdministration,Office Support
1,Receptionist,https://www.seek.co.nz/job/50620889?type=promo...,Avenues Orthodontics,Featured,Administration & Office SupportAdministration...,Bay of Plenty,Tauranga,Receptionists,Unknown,Administration,Office SupportAdministration,Office Support
2,Prosecutions Support Officer,https://www.seek.co.nz/job/50622169?type=stand...,New Zealand Police,4d ago,Administration & Office SupportAdministration...,Auckland,Unknown,Other,Unknown,Administration,Office SupportAdministration,Office Support
3,Early Childhood Centre Administrator,https://www.seek.co.nz/job/50639620?type=stand...,Kew Pacific Island Early Learning Centre,1h ago,Administration & Office SupportAdministration...,Southland,Invercargill,Administrative Assistants,Unknown,Administration,Office SupportAdministration,Office Support
4,Business Support Administrator,https://www.seek.co.nz/job/50622432?type=stand...,Private Advertiser,4d ago,Administration & Office SupportAdministration...,Canterbury,Christchurch,Client & Sales Administration,Unknown,Administration,Office SupportAdministration,Office Support
...,...,...,...,...,...,...,...,...,...,...,...,...
2703,Key Account Manager,https://www.seek.co.nz/job/50490062?type=stand...,Hays Talent Solutions,27d ago,Administration & Office SupportAdministration...,Auckland,Auckland Central,Client & Sales Administration,Unknown,Administration,Office SupportAdministration,Office Support
2704,Executive Assistant,https://www.seek.co.nz/job/50488000?type=stand...,one eighty recruitment,27d ago,Unknow,Wellington,Wellington Central,Unknown,Competitive hourly rate,Unknow,Unknown,Unknown
2705,Temporary Office Roles,https://www.seek.co.nz/job/50524865?type=stand...,Asset Recruitment Ltd,20d ago,Unknow,Waikato,Hamilton,Unknown,Competitive hourly rates $$,Unknow,Unknown,Unknown
2706,Temporary Office Roles,https://www.seek.co.nz/job/50477118?type=stand...,Asset Recruitment Ltd,28d ago,Unknow,Waikato,Hamilton,Unknown,Competitive hourly rates $$,Unknow,Unknown,Unknown
2707,Executive Assistant,https://www.seek.co.nz/job/50496571?type=stand...,Alpha Recruitment - NZ,26d ago,Administration & Office SupportAdministration...,Wellington,Unknown,"PA, EA & Secretarial",Unknown,Administration,Office SupportAdministration,Office Support

In [51]:
admin['Post Time'] = admin['Post Time'].str.extract('(\d+[a-z])')

In [52]:
admin

,Position,Link,Company,Post Time,Classification,Location,Area,SubClassification,Salary,Classification1,Classification2,Classification3
0,Administrator,https://www.seek.co.nz/job/50582301?type=promo...,Private Advertiser,NaN,Administration & Office SupportAdministration...,Bay of Plenty,Tauranga,Office Management,Unknown,Administration,Office SupportAdministration,Office Support
1,Receptionist,https://www.seek.co.nz/job/50620889?type=promo...,Avenues Orthodontics,NaN,Administration & Office SupportAdministration...,Bay of Plenty,Tauranga,Receptionists,Unknown,Administration,Office SupportAdministration,Office Support
2,Prosecutions Support Officer,https://www.seek.co.nz/job/50622169?type=stand...,New Zealand Police,4d,Administration & Office SupportAdministration...,Auckland,Unknown,Other,Unknown,Administration,Office SupportAdministration,Office Support
3,Early Childhood Centre Administrator,https://www.seek.co.nz/job/50639620?type=stand...,Kew Pacific Island Early Learning Centre,1h,Administration & Office SupportAdministration...,Southland,Invercargill,Administrative Assistants,Unknown,Administration,Office SupportAdministration,Office Support
4,Business Support Administrator,https://www.seek.co.nz/job/50622432?type=stand...,Private Advertiser,4d,Administration & Office SupportAdministration...,Canterbury,Christchurch,Client & Sales Administration,Unknown,Administration,Office SupportAdministration,Office Support
...,...,...,...,...,...,...,...,...,...,...,...,...
2703,Key Account Manager,https://www.seek.co.nz/job/50490062?type=stand...,Hays Talent Solutions,27d,Administration & Office SupportAdministration...,Auckland,Auckland Central,Client & Sales Administration,Unknown,Administration,Office SupportAdministration,Office Support
2704,Executive Assistant,https://www.seek.co.nz/job/50488000?type=stand...,one eighty recruitment,27d,Unknow,Wellington,Wellington Central,Unknown,Competitive hourly rate,Unknow,Unknown,Unknown
2705,Temporary Office Roles,https://www.seek.co.nz/job/50524865?type=stand...,Asset Recruitment Ltd,20d,Unknow,Waikato,Hamilton,Unknown,Competitive hourly rates $$,Unknow,Unknown,Unknown
2706,Temporary Office Roles,https://www.seek.co.nz/job/50477118?type=stand...,Asset Recruitment Ltd,28d,Unknow,Waikato,Hamilton,Unknown,Competitive hourly rates $$,Unknow,Unknown,Unknown
2707,Executive Assistant,https://www.seek.co.nz/job/50496571?type=stand...,Alpha Recruitment - NZ,26d,Administration & Office SupportAdministration...,Wellington,Unknown,"PA, EA & Secretarial",Unknown,Administration,Office SupportAdministration,Office Support

In [53]:
admin['Post Time'].fillna('Unknown', inplace = True)

In [54]:
admin['Post Time'] = admin['Post Time'].astype('string')

In [55]:
def apply_posted_time(x):
    if 'd' in x:
        return -int(x[:-1])
    if 'm' in x:
        return -(int(x[:-1])*30)
    else:
        return 0

In [56]:
admin['Post Time'] = admin['Post Time'].apply(apply_posted_time)

In [57]:
pd.set_option('display.max_colwidth', None)

In [58]:
admin[admin['Salary'].str.contains('\d', na = False)]['Salary']

12                           $20 per hour
17                  $20 - $24.99 per hour
23                    $19 to $22 per hour
25                  $20 - $24.99 per hour
36                  $20 - $24.99 per hour
                      ...
683     $35 - $40 p.h. + + 8% Holiday Pay
695                             Circa 50k
1936     $24 - $28 p.h.  + 8% Holiday Pay
1937    $35 - $40 p.h. + + 8% Holiday Pay
1949                            Circa 50k
Name: Salary, Length: 96, dtype: object

In [59]:
admin[admin['Salary'].str.contains('\dk', na = False)]['Salary']

306                                       $75k - $85k p.a.
442                     $60k-$70k depending on experience!
473     $60 - $65k + Career Progression to QS / leadership
644                      $50k - $65k p.a. + plus kiwisaver
650                                         $70-$80k+Super
663                                      $70-75k per annum
695                                              Circa 50k
1949                                             Circa 50k
Name: Salary, dtype: object

In [60]:
admin['Salary'] = admin[admin['Salary'].str.contains('\d', na = False)]['Salary'].str.replace(' to ', '-', regex = True)

In [61]:
admin[admin['Salary'].str.contains('\d\%', na = False)]['Salary'].head()

201                     8% holiday pay
311        $24 - $25 + 8% holiday pay!
384    $30 - $38 p.h. + 8% Holiday Pay
403     Up-$23 p.h. + + 8% Holiday Pay
458    $27 - $33 p.h. + 8% holiday pay
Name: Salary, dtype: object

In [62]:
admin['Salary'] = admin[admin['Salary'].str.contains('\d', na = False)]['Salary'].str.replace('\d+\%', '', regex = True)

In [63]:
admin['Salary'] = admin[admin['Salary'].str.contains('\d', na = False)]['Salary'].str.replace(',', '', regex = True)

In [64]:
admin[admin['Salary'].str.contains('\d', na = False)]['Salary'].head(50)

12                                    $20 per hour
17                           $20 - $24.99 per hour
23                                $19-$22 per hour
25                           $20 - $24.99 per hour
36                           $20 - $24.99 per hour
42                                 $40000 - $49999
48                                    $25 per hour
58                     $60 000 - $70 000 per annum
59                                 $20.00 per hour
66                           $20 - $24.99 per hour
75                                 $55000 - $69999
77                                $20.00 per hour.
78                           $20 - $24.99 per hour
81                                    $21 per hour
82                                 $55000 - $64999
89                   $50000 - $55000 plus benefits
97                                 $45000 - $49999
103             $55000 - $60000 per annum pro rata
112                          $20 - $24.99 per hour
114                          $20 - $24.99 per hour
123                                $48835 - $63221
134                          $20 - $29.99 per hour
148                                        $24-$28
156                                       Up-$27ph
165                  $50000 - $55000 plus benefits
171                          $20 - $29.99 per hour
173                          $20 - $29.99 per hour
191                          $20 - $24.99 per hour
212                                $55000 - $64999
214                                $40000 - $49999
219                                $45000 - $59999
231                         NZD25 - NZD28 per hour
247                          $20 - $24.99 per hour
264                                $45000 - $49999
277                                   $22 per hour
278                             NZD75000 per annum
282                          $20 - $24.99 per hour
306                               $75k - $85k p.a.
311                      $24 - $25 +  holiday pay!
318                                $40000 - $49999
319                              $50000 per annum.
346                                $55000 - $64999
349                             $20 - $25 per hour
379                          $20 - $24.99 per hour
384                  $30 - $38 p.h. +  Holiday Pay
393                                     $45-$55000
398                                $50000 - $54999
403                   Up-$23 p.h. + +  Holiday Pay
405                                 Up-$22.00 p.h.
430    NZD69726-94127p.a.+Retirement contributions
Name: Salary, dtype: object

In [65]:
admin[['Low_salary', 'High_salary']] = admin['Salary'].str.split('-', n = 1, expand = True).fillna('Unknown')

In [66]:
admin[admin['High_salary'].str.contains('\d', na = False)]['High_salary'].head(50)

17                                $24.99 per hour
23                                   $22 per hour
25                                $24.99 per hour
36                                $24.99 per hour
42                                         $49999
58                              $70 000 per annum
66                                $24.99 per hour
75                                         $69999
78                                $24.99 per hour
82                                         $64999
89                           $55000 plus benefits
97                                         $49999
103                     $60000 per annum pro rata
112                               $24.99 per hour
114                               $24.99 per hour
123                                        $63221
134                               $29.99 per hour
148                                           $28
156                                         $27ph
165                          $55000 plus benefits
171                               $29.99 per hour
173                               $29.99 per hour
191                               $24.99 per hour
212                                        $64999
214                                        $49999
219                                        $59999
231                                NZD28 per hour
247                               $24.99 per hour
264                                        $49999
282                               $24.99 per hour
306                                     $85k p.a.
311                           $25 +  holiday pay!
318                                        $49999
346                                        $64999
349                                  $25 per hour
379                               $24.99 per hour
384                       $38 p.h. +  Holiday Pay
393                                        $55000
398                                        $54999
403                     $23 p.h. + +  Holiday Pay
405                                   $22.00 p.h.
430            94127p.a.+Retirement contributions
442                 $70k depending on experience!
444                                    $23.00 phr
455                                        $49999
458                       $33 p.h. +  holiday pay
459                     $80K experience dependent
464                                  $22 per hour
473     $65k + Career Progression-QS / leadership
478                               $39.99 per hour
Name: High_salary, dtype: object

In [67]:
admin['Low_salary'] = admin['Low_salary'].str.extract('(\d+\.\d+|\d+ \d+|\d+k|\d+)')
admin['High_salary'] = admin['High_salary'].str.extract('(\d+\.\d+|\d+ \d+|\d+k|\d+)')

In [68]:
admin[admin['High_salary'].str.contains('\d', na = False)]['High_salary'].head(50)

17      24.99
23         22
25      24.99
36      24.99
42      49999
58     70 000
66      24.99
75      69999
78      24.99
82      64999
89      55000
97      49999
103     60000
112     24.99
114     24.99
123     63221
134     29.99
148        28
156        27
165     55000
171     29.99
173     29.99
191     24.99
212     64999
214     49999
219     59999
231        28
247     24.99
264     49999
282     24.99
306       85k
311        25
318     49999
346     64999
349        25
379     24.99
384        38
393     55000
398     54999
403        23
405     22.00
430     94127
442       70k
444     23.00
455     49999
458        33
459        80
464        22
473       65k
478     39.99
Name: High_salary, dtype: object

In [69]:
admin['Low_salary'] = admin[admin['Low_salary'].str.contains('\d', na = False)]['Low_salary'].str.replace('k', '000', regex = True)
admin['High_salary'] = admin[admin['High_salary'].str.contains('\d', na = False)]['High_salary'].str.replace('k', '000', regex = True)

In [70]:
pd.set_option('display.max_rows', 500)
admin[admin['Low_salary'].str.contains('\d', na = False)]['Low_salary'].head(100)

12          20
17          20
23          19
25          20
36          20
42       40000
48          25
58      60 000
59       20.00
66          20
75       55000
77       20.00
78          20
81          21
82       55000
89       50000
97       45000
103      55000
112         20
114         20
123      48835
134         20
148         24
165      50000
171         20
173         20
191         20
212      55000
214      40000
219      45000
231         25
247         20
264      45000
277         22
278      75000
282         20
306      75000
311         24
318      40000
319      50000
346      55000
349         20
379         20
384         30
393         45
398      50000
430      69726
442      60000
444      22.00
455      40000
458         27
459         60
464         19
473         60
478         35
482      55000
494         20
517         20
530         19
532      60000
533      40000
536         21
546      60000
550         21
558      50000
560         40
569      18.50
575       25.5
579         21
582         25
590         25
612      50000
625      50000
629         25
632      50000
633         20
641      48000
644      50000
650         70
653         20
656      45000
660      55000
663         70
679      45000
682         24
683         35
695      50000
1936        24
1937        35
1949     50000
Name: Low_salary, dtype: object

In [71]:
admin['Low_salary'] = admin[admin['Low_salary'].str.contains('\d', na = False)]['Low_salary'].str.replace(' ', '', regex = True)
admin['High_salary'] = admin[admin['High_salary'].str.contains('\d', na = False)]['High_salary'].str.replace(' ', '', regex = True)
admin['Low_salary'] = admin['Low_salary'].fillna('1')
admin['High_salary'] = admin['High_salary'].fillna('0')

In [72]:
admin[['Low_salary', 'High_salary']].head(400)

    Low_salary High_salary
0            1           0
1            1           0
2            1           0
3            1           0
4            1           0
5            1           0
6            1           0
7            1           0
8            1           0
9            1           0
10           1           0
11           1           0
12          20           0
13           1           0
14           1           0
15           1           0
16           1           0
17          20       24.99
18           1           0
19           1           0
20           1           0
21           1           0
22           1           0
23          19          22
24           1           0
25          20       24.99
26           1           0
27           1           0
28           1           0
29           1           0
30           1           0
31           1           0
32           1           0
33           1           0
34           1           0
35           1           0
36          20       24.99
37           1           0
38           1           0
39           1           0
40           1           0
41           1           0
42       40000       49999
43           1           0
44           1           0
45           1           0
46           1           0
47           1           0
48          25           0
49           1           0
50           1           0
51           1           0
52           1           0
53           1           0
54           1           0
55           1           0
56           1           0
57           1           0
58       60000       70000
59       20.00           0
60           1           0
61           1           0
62           1           0
63           1           0
64           1           0
65           1           0
66          20       24.99
67           1           0
68           1           0
69           1           0
70           1           0
71           1           0
72           1           0
73           1           0
74           1           0
75       55000       69999
76           1           0
77       20.00           0
78          20       24.99
79           1           0
80           1           0
81          21           0
82       55000       64999
83           1           0
84           1           0
85           1           0
86           1           0
87           1           0
88           1           0
89       50000       55000
90           1           0
91           1           0
92           1           0
93           1           0
94           1           0
95           1           0
96           1           0
97       45000       49999
98           1           0
99           1           0
100          1           0
101          1           0
102          1           0
103      55000       60000
104          1           0
105          1           0
106          1           0
107          1           0
108          1           0
109          1           0
110          1           0
111          1           0
112         20       24.99
113          1           0
114         20       24.99
115          1           0
116          1           0
117          1           0
118          1           0
119          1           0
120          1           0
121          1           0
122          1           0
123      48835       63221
124          1           0
125          1           0
126          1           0
127          1           0
128          1           0
129          1           0
130          1           0
131          1           0
132          1           0
133          1           0
134         20       29.99
135          1           0
136          1           0
137          1           0
138          1           0
139          1           0
140          1           0
141          1           0
142          1           0
143          1           0
144          1           0
145          1           0
146          1           0
147          1           0
148         24          28
149          1           0
150          1           0
151          1           0
152          1           0
153          1           0
154          1           0
155          1           0
156          1          27
157          1           0
158          1           0
159          1           0
160          1           0
161          1           0
162          1           0
163          1           0
164          1           0
165      50000       55000
166          1           0
167          1           0
168          1           0
169          1           0
170          1           0
171         20       29.99
172          1           0
173         20       29.99
174          1           0
175          1           0
176          1           0
177          1           0
178          1           0
179          1           0
180          1           0
181          1           0
182          1           0
183          1           0
184          1           0
185          1           0
186          1           0
187          1           0
188          1           0
189          1           0
190          1           0
191         20       24.99
192          1           0
193          1           0
194          1           0
195          1           0
196          1           0
197          1           0
198          1           0
199          1           0
200          1           0
201          1           0
202          1           0
203          1           0
204          1           0
205          1           0
206          1           0
207          1           0
208          1           0
209          1           0
210          1           0
211          1           0
212      55000       64999
213          1           0
214      40000       49999
215          1           0
216          1           0
217          1           0
218          1           0
219      45000       59999
220          1           0
221          1           0
222          1           0
223          1           0
224          1           0
225          1           0
226          1           0
227          1           0
228          1           0
229          1           0
230          1           0
231         25          28
232          1           0
233          1           0
234          1           0
235          1           0
236          1           0
237          1           0
238          1           0
239          1           0
240          1           0
241          1           0
242          1           0
243          1           0
244          1           0
245          1           0
246          1           0
247         20       24.99
248          1           0
249          1           0
250          1           0
251          1           0
252          1           0
253          1           0
254          1           0
255          1           0
256          1           0
257          1           0
258          1           0
259          1           0
260          1           0
261          1           0
262          1           0
263          1           0
264      45000       49999
265          1           0
266          1           0
267          1           0
268          1           0
269          1           0
270          1           0
271          1           0
272          1           0
273          1           0
274          1           0
275          1           0
276          1           0
277         22           0
278      75000           0
279          1           0
280          1           0
281          1           0
282         20       24.99
283          1           0
284          1           0
285          1           0
286          1           0
287          1           0
288          1           0
289          1           0
290          1           0
291          1           0
292          1           0
293          1           0
294          1           0
295          1           0
296          1           0
297          1           0
298          1           0
299          1           0
300          1           0
301          1           0
302          1           0
303          1           0
304          1           0
305          1           0
306      75000       85000
307          1           0
308          1           0
309          1           0
310          1           0
311         24          25
312          1           0
313          1           0
314          1           0
315          1           0
316          1           0
317          1           0
318      40000       49999
319      50000           0
320          1           0
321          1           0
322          1           0
323          1           0
324          1           0
325          1           0
326          1           0
327          1           0
328          1           0
329          1           0
330          1           0
331          1           0
332          1           0
333          1           0
334          1           0
335          1           0
336          1           0
337          1           0
338          1           0
339          1           0
340          1           0
341          1           0
342          1           0
343          1           0
344          1           0
345          1           0
346      55000       64999
347          1           0
348          1           0
349         20          25
350          1           0
351          1           0
352          1           0
353          1           0
354          1           0
355          1           0
356          1           0
357          1           0
358          1           0
359          1           0
360          1           0
361          1           0
362          1           0
363          1           0
364          1           0
365          1           0
366          1           0
367          1           0
368          1           0
369          1           0
370          1           0
371          1           0
372          1           0
373          1           0
374          1           0
375          1           0
376          1           0
377          1           0
378          1           0
379         20       24.99
380          1           0
381          1           0
382          1           0
383          1           0
384         30          38
385          1           0
386          1           0
387          1           0
388          1           0
389          1           0
390          1           0
391          1           0
392          1           0
393         45       55000
394          1           0
395          1           0
396          1           0
397          1           0
398      50000       54999
399          1           0

In [73]:
admin['Low_salary'] = admin['Low_salary'].astype('float32')
admin['High_salary'] = admin['High_salary'].astype('float32')

In [84]:
if admin['High_salary'] / admin['Low_salary'] > 1000:
    admin['Low_salary'] = admin['Low_salary'] * 1000

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().